trigger:
- main

pool:
  name: Default

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: Install dependencies

- script: |
    echo "Build successful"
  displayName: Run Build